# Generated by Django 5.2 on 2025-04-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]

def make_codes_unique(apps, schema_editor):
    Department = apps.get_model('erp_core', 'Department')
    
    # Find and fix duplicate codes
    from collections import defaultdict
    code_map = defaultdict(list)
    
    for dept in Department.objects.all():
        code_map[dept.code].append(dept)
    
    for code, depts in code_map.items():
        if len(depts) > 1:
            for i, dept in enumerate(depts[1:], 1):
                dept.code = f"{code}_{i}"
                dept.save()

class Migration(migrations.Migration):
    dependencies = [
        ('erp_core', '0001_initial'),  # Replace with your actual last migration
    ]

    operations = [
        migrations.RunPython(make_codes_unique),
    ]
