# Generated by Django 5.2 on 2025-04-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0002_alter_department_code'),
    ]

    operations = [
    ]
